from django.core.management.base import BaseCommand
from blog.models import Post



class Command(BaseCommand):
    help = 'Populate the database with blog posts'

    def handle(self, *args, **options):
        
        Post.objects.all().delete()
        img_urls = [
    'beefburger.jpg',
    'blackburger.jpg',
    'blackdonut.jpg',
    'burgerleaf.jpg',
    'butterburger.jpg',
    'cheesesandwich.jpg',
    'chickenburger.jpg',
    'chocodonut.jpg',
    'donut.jpg',
    'donut3.jpg',
    'firepizza.jpg',
    'flydonut.jpg',
    'half2sandwich.jpg',
    'halssandwich.jpg',
    'halfsandwich2.jpg',
    'layersandwich.jpg',
    'leafburger.jpg',
    'leafdonut.jpg',
    'leafpizza.jpg',
    'leafpizza2.jpg',
    'meetburger.jpg',
    'meetburger2.jpg',
    'nutdonut.jpg',
    'oniburger.jpg',
    'onimeetburger.jpg',
    'onionburger.jpg',
    'onitompizza.jpg',
    'piecepizza.jpg',
    'pinkdonut2.jpg',
    'pinkdonut.jpg',
    'sandwich.jpg',
    'sandwichcheese.jpg',
    'sandwichfries.jpg',
    'sauceburger.jpg',
    'slicepizza.jpg',
    'smallsandwich.jpg',
    'sprinkledonut.jpg',
    'stickburger.jpg',
    'tasteyburger.jpg',
    'tomatoburger.jpg',
    'tomatopizza.jpg',
    'tomatopizza2.jpg',
    'tomatopizza3.jpg',
    'tomatosandwich.jpg',
    'topburger.jpg',
    'topdonut.jpg',
    'whitecheeseburger.jpg',
    'whitemeetsand.jpg',
    'whitepizza.jpg',
    'whitepizza2.jpg',
    'woodpizza.jpg'
]

        titles = [
            'Delicious Beef Burger Recipe',
            'The Ultimate Black Burger Experience',
            'Irresistible Black Donut Delight',
            'Fresh Leafy Burger Extravaganza',
            'Creamy Butter Burger Bliss',
            'Cheesy Sandwich Sensation',
            'Crispy Chicken Burger Indulgence',
            'Decadent Choco Donut Temptation',
            'Classic Donut Delight',
            'Triple Layer Donut Indulgence',
            'Fiery Pizza Explosion',
            'Fly High with Our Donut Creation',
            'Half & Half Sandwich Surprise',
            'Half Sandwich, Full Flavor',
            'Half Sandwich, Double the Taste',
            'Layered Sandwich Masterpiece',
            'Leafy Burger Paradise',
            'Leafy Donut Dream',
            'Leafy Pizza Perfection',
            'Leafy Pizza Extravaganza',
            'Meaty Burger Marvel',
            'Meaty Burger Duo',
            'Nutty Donut Delight',
            'Onion Burger Bliss',
            'Onion Meet Burger Fusion',
            'Onion Burger Extravaganza',
            'Onion Topped Pizza Sensation',
            'Piece of Pizza Heaven',
            'Pink Donut Delight 2.0',
            'Pink Donut Delight',
            'Savory Sandwich Creation',
            'Cheesy Sandwich Delight',
            'Fries-Filled Sandwich Surprise',
            'Saucy Burger Sensation',
            'Slice of Pizza Paradise',
            'Small Sandwich, Big Flavor',
            'Sprinkled Donut Delight',
            'Stick Burger Sensation',
            'Tasty Burger Temptation',
            'Tomato Burger Bliss',
            'Tomato Pizza Perfection',
            'Tomato Pizza Extravaganza',
            'Tomato Sandwich Sensation',
            'Top Burger Experience',
            'Top Donut Delight',
            'White Cheese Burger Indulgence',
            'White Meat Sandwich Sensation',
            'White Pizza Paradise',
            'White Pizza Extravaganza',
            'Wood-Fired Pizza Delight'
        ]

        contents = [
    'Learn how to make a delicious beef burger with our easy recipe.',
    'Experience the bold flavors of our ultimate black burger.',
    'Indulge in the irresistible taste of our black donut delight.',
    'Enjoy a fresh and healthy leafy burger with our special recipe.',
    'Discover the creamy goodness of our butter burger recipe.',
    'Savor the cheesy delight of our sandwich recipe.',
    'Try our crispy chicken burger recipe for a tasty meal.',
    'Treat yourself to the decadent taste of our choco donut recipe.',
    'Make classic donuts at home with our simple recipe.',
    'Indulge in a triple layer of donut goodness with our recipe.',
    'Spice up your pizza night with our fiery pizza recipe.',
    'Take your taste buds flying with our unique donut creation.',
    'Surprise your taste buds with our half & half sandwich recipe.',
    'Enjoy full flavor with our half sandwich recipe.',
    'Double the taste with our half sandwich recipe.',
    'Create a layered sandwich masterpiece with our recipe.',
    'Experience burger paradise with our leafy burger recipe.',
    'Dream big with our leafy donut recipe.',
    'Perfect your pizza with our leafy pizza recipe.',
    'Extravaganza of flavors with our leafy pizza recipe.',
    'Marvel at the meaty goodness of our burger recipe.',
    'Double the meaty delight with our burger recipe.',
    'Delight in the nutty flavors of our donut recipe.',
    'Savor the bliss of our onion burger recipe.',
    'Fusion of flavors in our onion meet burger recipe.',
    'Experience the extravaganza of our onion burger recipe.',
    'Sensation of flavors with our onion topped pizza recipe.',
    'Heavenly taste with our piece of pizza recipe.',
    'Delight in the pink donut with our special recipe.',
    'Enjoy the delightful taste of our pink donut recipe.',
    'Create a savory sandwich with our easy recipe.',
    'Delight in the cheesy goodness of our sandwich recipe.',
    'Surprise your taste buds with our fries-filled sandwich recipe.',
    'Experience the saucy sensation of our burger recipe.',
    'Paradise in every slice with our pizza recipe.',
    'Big flavor in a small sandwich with our recipe.',
    'Delight in the sprinkled goodness of our donut recipe.',
    'Sensation of flavors with our stick burger recipe.',
    'Tempt your taste buds with our tasty burger recipe.',
    'Blissful flavors in our tomato burger recipe.',
    'Perfect your pizza with our tomato pizza recipe.',
    'Extravaganza of flavors with our tomato pizza recipe.',
    'Sensation of flavors with our tomato sandwich recipe.',
    'Experience the ultimate top burger with our recipe.',
    'Delight in the top donut with our special recipe.',
    'Indulge in the white cheese burger with our recipe.',
    'Sensation of flavors with our white meat sandwich recipe.',
    'Paradise in every bite with our white pizza recipe.',
    'Extravaganza of flavors with our white pizza recipe.',
    'Delight in the wood-fired goodness of our pizza recipe.'

]

        for title, content, img_url in zip(titles, contents, img_urls):
            Post.objects.create(title=title, content=content, img_url=img_url)
        self.stdout.write(self.style.SUCCESS('Successfully populated posts'))